name: mi_app_optativa
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  charts_flutter: ^0.12.0
  http: ^1.1.0
  provider: ^6.1.2
  collection: ^1.15.0
  flutter_blurhash: ^0.6.0
  firebase_core: ^2.3.0
  firebase_storage: ^11.6.0
  firebase_auth: ^4.1.0 
  image_picker: ^0.8.5+3
  cloud_firestore: ^4.3.0
  path_provider: ^2.0.2
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_image: ^4.1.11  
  flutter_native_image: ^0.0.6
  flutter_image_editor: ^2.1.0
  image_cropper: ^5.0.1
  image_editor: ^1.5.1
  image: ^4.2.0
  image_gallery_saver: ^2.0.3
  flutter_web_browser: ^0.17.1
  camera: ^0.10.0+2
  crop: ^0.5.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - galery/
    - images/
  fonts:
    - family: FredokaOne
      fonts:
        - asset: fonts/FredokaOne-Regular.ttf 
    - family: PermanentMarker
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf      
